let data = [
{
    id : 0,
    title : "나이키 에어 포스 1 '07",
    content : "남성 신발",
    price : 139000,
    url: '/img/item00.webp',
    productInfo: "빛이 그래도 살아 있는 나이키 에어 포스 1 '07은 OG 농구화로서 많은 사랑을 받아온 디자인에 새로운 멋을 더했습니다. 튼튼하게 스티치 처리된 오버레이와 깔끔한 마감 처리, 과하지 않은 절제된 화려함으로빛나는 존재감을 발휘해 보세요.",
    productColor1: "현재 컬러 : 화이트/화이트",
    productColor2: "스타일 번호 : CW2288-111",
    productTitle00: "에어 포스",
    productTitle01: "상품 특징",
    productTitle02: "전설적인 스타일, 새로운 감각",
    productTitle03: "상품 상세 정보",
    productGood01: "갑피의 스티치된 오버레이로 내구성과 지지력을 제공하며 헤리티지 스타일 선사",
    productGood02: "본래 퍼포먼스 농구화를 위해 고안된 나이키 에어 쿠셔닝이 온종일 가볍고 편안한 착화감 선사합니다.",
    productGood03: "로우컷 실루엣이 깔끔하고 매끈한 룩 연출",
    productGood04: "부드럽고 편안한 패딩 카라",
    proInfo01: "ㆍ폼 중창",
    proInfo02: "ㆍ토의 천공 디테일",
    proInfo03: "ㆍ고무 밑창",
    historyTit: "에어 포스 1에 대하여",
    history: "1982년에 첫선을 보인 AF1은 나이키 에어를 장착한 최초의 농구화로 경기에 혁신을 일으키며 짧은 시간 내 전 세계적인 관심을 받았습니다. 스니커즈의 역사에 변화를 가져온 부드럽고 탄력 있는 쿠셔닝은 오늘날의 에어 포스 1에도 고스란히 전해지고 있습니다.",

    infoImgTit01: "전설적인 스타일의 신선한 재해석.",
    infoImgTit02: "우븐 라벨 대신 음각으로 디자인",
    infoImgTit03: "모델 정보",
    infoImgTitSub01: "낡아가는 과정은 막을 수 없다고 하지만 에어 포스 1 ‘프레시’는 제법 근접한 효과를 발휘합니다. 부드럽고 텍스처가 살아있는 가죽은 주름을 가려주고 세척이 편리합니다.",
    infoImgTitSub02: "우븐 라벨 대신 음각으로 새긴 브랜딩은 여분의 신발 끈과 어우러져 잼 도넛도 마음 놓고 먹을 수 있습니다. 천공 깔창은 쾌적하고 통기성이 좋습니다. 이제 화이트 온 화이트 스타일을 즐기지 못할 이유가 없겠죠.",
    infoImgTitSub03: "남자 모델 키 : 186cm, 착용 사이즈 : 275",
    infoImg01: '/img/info_img/pos_01.jpg',
    infoImg02: '/img/info_img/pos_02.jpg',
    infoImg03: '/img/info_img/pos_03.jpg',
},
{
    id : 1,
    title : "나이키 페가수스 트레일4",
    content : "남성 워터프루프 트레일 러닝화",
    price : 189000,
    url: '/img/item01.webp',
    productInfo: "나이키 페가수스 트레일 4 GORE-TEX는 변덕스러운 날씨에 적합한 러닝 파트너입니다. 생활 방수 GORE-TEX 레이어가 발을 쾌적하게 유지해 주며, 밑창에 적용된 고무가 적어 발걸음을 멈추지 않고도 도로에서 트레일로 자연스럽게 옮겨갈 수 있습니다.",
    productColor1: "현재 컬러 : 블랙/리플렉트 실버/울프 그레이",
    productColor2: "스타일 번호 : DJ7926-001",
    productTitle00: "나이키 페가수스 트레일 4",
    productTitle01: "비 오는 날도 걱정 없이",
    productTitle02: "트레일에 고무가 닿는 순간",
    productTitle03: "상품 상세 정보",
    productGood01: "갑피의 GORE-TEX 덕분에 페가수스 트레일의 편안한 착화감을 잃지 않고도 비가 올 때 한결같이 쾌적합니다. 유연한 경량 디자인으로 젖은 도로와 트레일에서 러닝할 때도 비를 차단해 줍니다.",
    productGood02: "밑창의 고무를 줄여 로드에서 트레일로 향할 때 한층 전환이 자연스럽고 전체 길이 리액트 중창은 그대로 유지했습니다. 고무 밑창으로 신발 앞면을 감싸 내구성을 강화했습니다. 앞꿈치 고무와 제너레이티브 접지 패턴이 결합하여 테크니컬 트레일에서 그립력이 향상되었고 도로에서 매끄러운 느낌을 유지합니다.",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ신발에 따라 'JUST DO IT'과 'JUST RUN IT'으로 다르게 적용되어 영감을 주는 뒤꿈치의 메시지",
    proInfo02:"ㆍ힐과 설포의 풀 탭",
    proInfo03:"ㆍ개인 보호 장비(PPE) 용도로 사용하지 말 것",
    proInfo04:"",
    historyTit: "",
    history: "",

    infoImgTit01: "침착함을 유지하기",
    infoImgTit02: "도로에서 트레일까지",
    infoImgTit03: "모델 정보",
    infoImgTitSub01: "도로에서 트레일까지 러닝할 때는 지면에 상관없이 계속 앞으로 나아가게 하는 신발이 필요합니다. 새로운 나이키 리액트 페가수스 트레일 4를 신고 러닝을 해보세요. 트레일 러너들이 신뢰하는 신발입니다.",
    infoImgTitSub02: "일체형 플라이와이어 기술로 탁월한 지지력을 제공하고, 나이키 리액트 폼으로 반응성이 뛰어난 착화감을 선사하며, 고무 밑창으로 내구성을 강화합니다. 나이키 리액트 페가수스 트레일 4의 모든 디테일은 앞으로 펼쳐질 모험과 러닝을 즐길 수 있도록 디자인되었습니다.",
    infoImgTitSub03: "남자 모델 : 177cm, 착용 사이즈 : 270",
    infoImg01: '/img/info_img/fg_01.jpg',
    infoImg02: '/img/info_img/fg_02.jpg',
    infoImg03: '/img/info_img/fg_03.jpg',
},
{
    id : 2,
    title : "나이키 덩크 로우 레트로",
    content : "남성 신발",
    price : 129000,
    url: '/img/item02.webp',
    productInfo: "하드우드를 위해 태어나 스트리트로 무대를 옮겨온 나이키 덩크 로우 레트로가 산뜻한 오버레이와 오리지널 팀 컬러로 돌아왔습니다. 신을수록 부드러워지는 멋진 룩의 프리미엄 가죽 갑피가 특징인 이 농구 아이콘은 80년대 분위기를 한껏 발산합니다. 여기에 현대의 풋웨어 기술로 21세기의 편안함을 구현했습니다.",
    productColor1: "현재 컬러 : 화이트/화이트/블랙",
    productColor2: "스타일 번호 : DD1391-100",
    productTitle00: "나이키 덩크 로우 레트로",
    productTitle01: "상품 특징",
    productTitle02: "진정한 팀워크를 위해.",
    productTitle03: "상품 상세 정보",
    productGood01: "하드우드를 위해 태어나 스트리트로 무대를 옮겨온 나이키 덩크 로우 레트로가 산뜻한 오버레이와 오리지널 팀 컬러로 돌아왔습니다. 신을수록 부드러워지는 멋진 룩의 프리미엄 가죽 갑피가 특징인 이 농구 아이콘은 80년대 분위기를 한껏 발산합니다. 여기에 현대의 풋웨어 기술로 21세기의 편안함을 구현했습니다.",
    productGood02: "길들이면서 더욱 아름다워지는 완벽한 광택의 프리미엄 가죽 갑피",
    productGood03: "현대적인 폼 중창으로 가볍고 반응성이 우수한 쿠셔닝 선사",
    productGood04: "스쿨 팀 컬러의 과감한 컬러 블로킹으로 오리지널 컬러웨이 감성 재현",
    proInfo01:"ㆍ로우 컷 카라",
    proInfo02:"ㆍ폼 안창",
    proInfo03:"ㆍ토의 천공 디테일",
    proInfo04:"",
    historyTit: "",
    history: "",

    infoImgTit01: "진정한 팀워크를 위해.",
    infoImgTit02: "나이키 덩크",
    infoImgTit03: "",
    infoImgTitSub01: "하드우드를 위해 탄생하여 스트리트로 무대를 옮겨온 80년대의 농구 아이콘이 클래식한 팀 컬러와 완벽한 광택이 돋보이는 오버레이와 함께 돌아왔습니다.",
    infoImgTitSub02: "현대적인 폼 중창은 가볍고 반응성이 우수한 쿠셔닝을 선사합니다",
    infoImgTitSub03: "패딩 처리된 로우컷 카라가 편안한 느낌을 주는 날렵한 룩을 완성합니다.",
    infoImg01: '/img/info_img/don_01.jpg',
    infoImg02: '/img/info_img/don_02.jpg',
    infoImg03: '/img/info_img/don_03.jpg',
},
{
    id : 3,
    title : "나이키 에어맥스 1 '86 OG G",
    content : "남성 골프화",
    price : 179000,
    url: '/img/item03.webp',
    productInfo: "에어맥스 1 G로 스트리트웨어의 전설을 골프화로 재해석했습니다. 4개의 윈도우가 있는 디자인으로 발 아래의 대형 에어 유닛을 들여다 볼 수 있으며, 코스에서 멋스러움과 자신감, 편안함을 선사합니다. 깔끔한 라인과 선명한 컬러 등 많은 사랑을 받은 빈티지 에어맥스 1의 디테일이 나이키의 획기적인 골프 기술과 잘 어우러져 시대를 초월하는 핏으로 하루 종일 플레이할 수 있습니다.",
    productColor1: "현재 컬러 : 화이트/뉴트럴 그레이/블랙/유니버시티 레드",
    productColor2: "스타일 번호 : DV1403-160",
    productTitle00: "에어맥스 1 G",
    productTitle01: "",
    productTitle02: "투명 맥스 에어",
    productTitle03: "상품 상세 정보",
    productGood01: "",
    productGood02: "발을 내디딜 때마다 최적의 쿠셔닝을 한눈에 확인할 수 있도록 4개의 창을 더한 디자인이 특징입니다. 뒤꿈치에 음각 처리된 'Nike Air' 로고 등 디자인 디테일은 1986년 출시된 에어맥스 1의 시대를 초월하는 룩에서 영감을 받았습니다.",
    productGood03: "합성 소재 갑피가 어떤 날씨에도 내수 기능을 제공합니다.",
    productGood04: "",
    proInfo01:"ㆍ생활 방수 기능 보증 기간: 1년",
    proInfo02:"ㆍ오래 신을 수 있도록 강화된 내구성",
    proInfo03:"ㆍ스파이크 없음",
    proInfo04:"ㆍ전체적으로 적용된 폼 중창",
    historyTit: "",
    history: "",

    infoImgTit01: "Big Bubble",
    infoImgTit02: "Heritage",
    infoImgTit03: "새로운 시작 환영",
    infoImgTitSub01: "스니커즈의 문화와 역사가 바로 여기, 에어맥스 1 'Big Bubble(빅 버블)'에서 시작됩니다.",
    infoImgTitSub02: "하나의 혁명을 기억합니다. 1987년은 육안으로 확인할 수 있는 투명 에어를 최초로 장착한 에어맥스의 계보가 시작된 해입니다. 쿠셔닝에 대한 실험으로 시작된 디자인은 얼마 지나지 않아 경기장에서, 그리고 길거리에서 시선을 사로잡는 하나의 아이콘으로 진화했습니다. 수년 간 다양한 방식으로 재해석되고 개편됐지만, 에어맥스 고유의 헤리티지는 그대로 유지되어 왔습니다.",
    infoImgTitSub03: "첫 출시 이후 지금 우리가 알고 있는 에어맥스 1이 오리지널을 조용히 대체했고, 에어맥스 제품군의 리더로 자리매김하게 되었습니다. 그렇게 소리 소문 없이 사라진 줄만 알았던 'Big Bubble(빅 버블)'의 새로운 시작을 환영합니다.",
    infoImg01: '/img/info_img/air_01.jpg',
    infoImg02: '/img/info_img/air_02.jpg',
    infoImg03: '/img/info_img/air_03.jpg',
},
{
    id : 4,
    title : "나이키 메트콘 8",
    content : "남성 트레이닝 화",
    price : 159000,
    url: '/img/item04.webp',
    productInfo: "목표와 성과를 달성하기 위해 바쁘게 움직이며 도전하고 서로를 격려하는 당신. 이 믿을 수 있는 나이키 트레이닝화는 이전 버전보다 더 가볍고 통기성이 뛰어난 갑피를 적용해 내구성과 편안함에 관한 나이키의 기준을 충족합니다. 유산소 운동은 더욱 가볍게, 리프팅은 더욱 힘차게 하며 운동을 자신감 있게 즐겨 보세요",
    productColor1: "현재 컬러 : 화이트/브라이트 크림슨/옵시디언",
    productColor2: "스타일 번호 : DO9328-101",
    productTitle00: "나이키 메트콘 8",
    productTitle01: "",
    productTitle02: "탄성이 느껴지는 발걸음",
    productTitle03: "추가 특징",
    productGood01: "", 
    productGood02: "매끄럽고 반응성이 탁월한 나이키 리액트 폼은 힘차게 유산소 운동과 전력 질주를 할 때 가볍고 탄력 있는 느낌을 주는 편안한 쿠션 베이스를 형성합니다.",
    productGood03: "",
    productGood04: "",
    proInfo01: "ㆍ탈부착 스트랩을 이용해 탭으로 신발 끈을 고정하여 방해 요소 차단",
    proInfo02: "ㆍ뒤꿈치의 핸드스탠드 클립이 벽 운동 중 끌리는 현상 최소화",
    proInfo03: "ㆍ앞꿈치를 자연스럽게 구부릴 수 있도록 적용된 밑창의 홈",
    proInfo04: "",
    historyTit: "",
    history: "",
    
    infoImgTit01: "탄성이 느껴지는 발걸음",
    infoImgTit02: "가볍고 탄력 있는 느낌을 주는 편안한 쿠션 베이스",
    infoImgTit03: "모델 정보",
    infoImgTitSub01: "모든 각도에서 발휘되는 그립력",
    infoImgTitSub02: "그립감 좋은 고무가 고강도 로프 클라이밍 시 아치를 감싸줍니다. 고무 트레드는 트레이닝 룸 바닥에서부터 포장도로에서까지 접지력과 고정력을 제공합니다.",
    infoImgTitSub03: "여자 모델 키 : 173, 착용 사이즈 240",
    infoImg01: '/img/info_img/mt_02.jpg',
    infoImg02: '/img/info_img/mt_02.jpg',
    infoImg03: '/img/info_img/mt_03.jpg',
},
{
    id : 5,
    title : "나이키 티엠포 레전드 9 엘리트 FG",
    content : "천연 잔디 클리트 축구화",
    price : 242100,
    url: '/img/item05.webp',
    productInfo: "지금껏 가장 가벼운 티엠포 모델 중 하나인 나이키 티엠포 레전드 9 엘리트 FG는 공격수를 위해 새롭게 개발된 로우 프로파일 디자인으로 선제 공격에 나설 수 있게 해 줍니다. 부드러운 폼 포드로 표면의 텍스처를 볼록하게 처리한 갑피가 드리블, 패스, 슈팅의 정확도를 높여 주며, 바닥의 스터드는 민첩한 컷 동작과 급정지를 위한 접지력을 제공합니다.",
    productColor1: "현재 컬러 : 블랙/서밋 화이트/라이트 포토 블루/다크 스모크 그레이",
    productColor2: "스타일 번호 : CZ8482-001",
    productTitle00: "나이키 티엠포 레전드 9 엘리트 FG",
    productTitle01: "가장 가벼운 레전드 중 하나.",
    productTitle02: "더욱 가벼워진 레전드",
    productTitle03: "상품 상세 정보",
    productGood01: "지금껏 가장 가벼운 티엠포 모델 중 하나인 나이키 티엠포 레전드 9 엘리트 FG는 공격수를 위해 새롭게 개발된 로우 프로파일 디자인으로 선제 공격에 나설 수 있게 해 줍니다. 부드러운 폼 포드로 표면의 텍스처를 볼록하게 처리한 갑피가 드리블, 패스, 슈팅의 정확도를 높여 주며, 바닥의 스터드는 민첩한 컷 동작과 급정지를 위한 접지력을 제공합니다.",
    productGood02: "새롭게 디자인된 플레이트와 정밀한 갑피로 부피를 줄여 필드에서 빠르게 공격할 수 있습니다.",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ약간 축축하고 잔디가 짧은 구장에 적합",
    proInfo02:"ㆍ쿠션 처리된 안창",
    proInfo03:"ㆍ제조 국가/지역: 베트남",
    proInfo04:"",
    historyTit: "",
    history: "",

    infoImgTit01: "매우 부드러운 가죽",
    infoImgTit02: "더욱 빨라진 레전드",
    infoImgTit03: "",
    infoImgTitSub01: "부드러운 폼 포드를 덧댄 가죽 갑피가 슈팅의 정확도를 높여줍니다.",
    infoImgTitSub02: "새롭게 디자인된 플레이트와 정밀한 갑피로 부피감을 줄여 필드에서 빠르게 공격할 수 있습니다.",
    infoImgTitSub03: "",
    infoImg01: '/img/info_img/re_01.jpg',
    infoImg02: '/img/info_img/re_02.jpg',
    infoImg03: '',
},
{
    id : 6,
    title : "나이키 TC 7900",
    content : "여성 신발",
    price : 111200,
    url: '/img/item06.webp',
    productInfo: "일상에서 튼튼하게 신을 수 있도록 제작된 나이키 TC 7900은 여정에 나설 준비를 마쳤습니다. 패딩 처리된 카라와 부드러운 폼 쿠셔닝이 지속적인 편안함을 선사합니다.",
    productColor1: "현재 컬러 : 세일/블랙/세일",
    productColor2: "스타일 번호 : DD9682-100",
    productTitle00: "나이키 TC 7900",
    productTitle01: "일상의 튼튼한 동반자.",
    productTitle02: "강인하고 튼튼한 디자인",
    productTitle03: "추가 특징",
    productGood01: "일상에서 튼튼하게 신을 수 있도록 제작된 나이키 TC 7900은 여정에 나설 준비를 마쳤습니다. 패딩 처리된 카라와 부드러운 폼 쿠셔닝이 지속적인 편안함을 선사합니다.",
    productGood02: "갑피에 여러 겹의 합성 소재를 사용해 내구성을 극대화했습니다. 웨빙 디테일과 힐의 고무 액센트가 강인한 룩을 완성합니다",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ두 개의 풀 탭으로 신발을 신고 벗기 용이",
    proInfo02:"ㆍ날렵한 룩과 편안한 착화감을 선사하는 로우 컷 패딩 카라",
    proInfo03:"",
    proInfo04:"",
    historyTit: "",
    history: "",

    infoImgTit01: "",
    infoImgTit02: "",
    infoImgTit03: "모델 정보",
    infoImgTitSub01: "",
    infoImgTitSub02: "",
    infoImgTitSub03: "여자 모델 키 : 168cm, 착용 사이즈 : 240",
    infoImg01: '/img/info_img/tc_01.jpg',
    infoImg02: '/img/info_img/tc_02.jpg',
    infoImg03: '/img/info_img/tc_03.jpg',
},
{
    id : 7,
    title : "르브론 XX EP",
    content : "농구화",
    price : 239000,
    url: '/img/item07.webp',
    productInfo: "약 20년 동안의 커리어에서 무엇을 기대하든 그 이상을 보여 준 르브론 제임스는 최고의 자리에서도 안주하지 않고 더 높은 이상을 추구해 왔습니다. 새로운 그의 시그니처 슈즈는 더욱 가볍고, 높이가 낮으며, 터보와 같은 스타일로 제작됐습니다. 지금까지의 르브론과는 다른, 완전히 새로운 디자인을 적용하여 편안함과 지지력을 제공하면서도 로우 컷과 깃털 같은 속도감은 유지하여 오늘날의 현란한 플레이 스타일을 주도해 나갈 수 있습니다. 이 버전은 내구성이 뛰어난 고무 밑창을 이용해 야외 코트용으로 제작되었습니다.",
    productColor1: "현재 컬러 : 블랙/화이트/퓨어 플래티넘/메탈릭 골드",
    productColor2: "스타일 번호 : DJ5422-003",
    productTitle00: "르브론 XX EP",
    productTitle01: "",
    productTitle02: "통기성을 높여주는 탑",
    productTitle03: "상품 상세 정보",
    productGood01: "",
    productGood02: "갑피의 통기성 좋은 소재는 가볍지만 내구성이 좋으며 발을 단단히 감싸주는 입체적인 니트 메쉬로 제작되었습니다.",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ발 앞부분을 지지하는 랩 웨지",
    proInfo02:"ㆍ스피어 안감 카라",
    proInfo03:"ㆍ메탈 아일릿",
    proInfo04:"ㆍ개인 보호 장비(PPE) 용도로 사용하지 말 것",
    historyTit: "",
    history: "",

    infoImgTit01: "핑크 다이아몬드의 고귀함",
    infoImgTit02: "매끄럽고 반응성 좋은 착화감",
    infoImgTit03: "통기성 좋은 갑피",
    infoImgTitSub01: "르브론의 커리어는 엄청난 압력을 거쳐 형성되어 마침내 아름답게 빛나는 핑크 다이아몬드를 떠올리게 합니다. 로즈 계열 색조에서 받은 영감을 챔피언십 링에 이르는 르브론의 뛰어난 업적과 연결 지어 압박감을 동기로 승리를 쟁취해 낼 수 있음을 표현하고자 했습니다.",
    infoImgTitSub02: "발 앞부분의 대형 줌 에어 유닛은 여러 방향으로 구부러지는 곡선형으로 만들어졌습니다. 이를 통한 에너지 반환으로 신속하고 반응성 좋은 코너링이 가능하며, 유연한 코트 감각으로 발과 함께 자연스럽게 움직입니다. 아래에서 넣은 방식의 뒤꿈치 줌 에어 유닛이 쿠셔닝을 더해줍니다.",
    infoImgTitSub03: "갑피의 통기성 좋은 소재는 가볍지만 내구성이 좋으며 발을 단단히 감싸주는 입체적인 니트 메쉬로 제작되었습니다.",
    infoImg01: '/img/info_img/ep_01.jpg',
    infoImg02: '/img/info_img/ep_02.jpg',
    infoImg03: '/img/info_img/ep_03.jpg',
},
{
    id : 8,
    title : "나이키 에어맥스 AP",
    content : "여성 신발",
    price : 129000,
    url: '/img/item08.webp',
    productInfo: "과거와 현재를 이어주는 세련되고 스포티한 디자인과 최상급 편안함을 선사하는 나이키 에어맥스 AP를 만나보세요. 에어맥스 97의 헤리티지를 느낄 수 있는 디테일에 깔끔한 갑피와 더욱 부드러운 중창으로 현대적인 감성을 더했습니다. 푹신한 패딩 카라, 통풍이 잘되는 메쉬 및 편안한 안창을 더한 로우 프로파일 디자인은 어떤 의상과도 잘 어울립니다.",
    productColor1: "현재 컬러: 화이트/화이트/씨 코랄",
    productColor2: "스타일 번호 CU4870-109:",
    productTitle00: "과거와 현재를 잇는 완벽한 조화.",
    productTitle01: "상품 특징",
    productTitle02: "",
    productTitle03: "상품 상세 정보",
    productGood01: "본래 퍼포먼스 러닝화를 위해 고안된 전체 길이의 혁신적인 에어 유닛이 날렵한 로우 프로파일 디자인과 새로운 감각 전달",
    productGood02: "",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ뒤꿈치와 토의 반사체 천공",
    proInfo02:"ㆍ개인 보호 장비(PPE) 용도로 사용하지 말 것",
    proInfo03:"ㆍTPU 스우시",
    proInfo04:"ㆍ편안한 안창",
    historyTit: "나이키 에어맥스에 대하여",
    history: "혁명적인 에어 기술은 1978년 처음으로 나이키 신발에 적용되었습니다. 1987년에는 에어맥스 1의 힐을 통해 투명 에어 기술이 최초로 등장하여 팬들이 에어의 쿠셔닝을 느낄 뿐만 아니라 눈으로 직접 확인할 수 있게 되었습니다. 그 이후, 다음 세대의 에어맥스 신발들은 매력적인 컬러 조합과 신뢰할 수 있는 경량 쿠셔닝을 제공하여 운동선수와 수집가들에게 큰 인기를 얻고 있습니다.",

    infoImgTit01: "나이키 에어맥스 AP",
    infoImgTit02: "모델 정보",
    infoImgTitSub01: "",
    infoImgTitSub02: "여자 모델 키 : 170cm, 착용사이즈 : 240",
    infoImg01: '/img/info_img/ap_01.jpg',
    infoImg02: '/img/info_img/ap_02.jpg',
    infoImg03: '/img/info_img/ap_03.jpg',
},
{
    id : 9,
    title : "나이키 에어 포스 1 쉐도우",
    content : "여성 신발",
    price : 159000,
    url: '/img/item09.webp',
    productInfo: "걸음마다 유니크한 개성을 선사합니다. 이 신발은 모두가 사랑하는 AF1의 특징을 두 배로 강화해 농구 아이콘에 경쾌한 감성을 더했습니다. 리넨을 연상시키는 직물과 인조 가죽을 레이어드한 소재에 과장된 중창과 파스텔 색조를 더해 두 배로 멋진 스타일을 선사합니다.",
    productColor1: "현재 컬러: 서밋 화이트/울프 그레이/퓨어 플래티넘/세서미",
    productColor2: "스타일 번호 : DV7449-100",
    productTitle00: "나이키 에어 포스 1 쉐도우",
    productTitle01: "상품 상세 정보",
    productTitle02: "",
    productTitle03: "상품 특징",
    productGood01: "폼 중창, 제조 국가/지역: 중국",
    productGood02: "",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ아이스테이, 머드가드, 스우시 로고를 2개씩 적용한 디자인으로 브랜딩을 두 배로 강조한 감각적인 레이어드 룩 연출",
    proInfo02:"ㆍ스티치 처리된 가죽 오버레이로 내구성을 높이고 헤리티지 룩에 텍스처를 더한 디자인",
    proInfo03:"ㆍ본래 퍼포먼스 농구화를 위해 고안된 나이키 에어 쿠셔닝이 지속적으로 편안한 착화감 선사",
    proInfo04:"",
    historyTit: "에어 포스 1",
    history: "농구 필수 아이템으로 1982년에 출시된 에어 포스 1은 90년대부터 많은 사랑을 받기 시작했습니다. 클래식한 화이트 온 화이트의 AF1이 선보이는 깔끔한 룩은 농구 코트에서부터 스트리트, 일상에 이르기까지 그 인기를 증명했습니다. 에어 포스 1은 힙합 문화에서 자리를 잡고 한정판 컬래버레이션 아이템과 컬러웨이를 선보이며 전 세계적으로 아이코닉한 스니커즈로 성장했습니다. 2,000가지 이상의 버전으로 출시된 이 필수 아이템이 패션과 음악, 스니커즈 문화에 미친 영향은 부정할 수 없습니다.",

    infoImgTit01: "향상된 스타일",
    infoImgTit02: "오랜 시간을 거쳐 검증된 스타일",
    infoImgTit03: "탁월한 성능과 편안함",
    infoImgTitSub01: "위로 들린 중창은 에어포스 시리즈에 새로운 입체감을 제공하여 손쉬운 스타일링과 멋진 룩을 선사합니다. 발 아래의 부드러운 폼은 편안함을 더합니다.",
    infoImgTitSub02: "에어 포스 1은 40년 동안 많은 사람들이 즐겨 찾는 신발이었습니다. 큰 사랑을 받은 선명한 가죽, 헤리티지 디테일, 기능적인 편안함과 같은 특징은 그대로 간직해 시간이 지나도 계속해서 착용할 수 있는 타임리스 룩을 완성했습니다.",
    infoImgTitSub03: "본래 퍼포먼스 농구화를 위해 디자인된 뒤꿈치의 에어 쿠셔닝이 오래도록 편안한 착화감을 선사합니다.",
    infoImg01: '/img/info_img/sapo_01.jpg',
    infoImg02: '/img/info_img/sapo_02.jpg',
    infoImg03: '/img/info_img/sapo_03.jpg',
},
{
    id : 10,
    title : "나이키 에어 포스 1 '07 LX",
    content : "여성 신발",
    price : 159000,
    url: '/img/item010.webp',
    productInfo: "어디에서든 경기를 향한 애정을 표현하세요. 하드우드의 편안함과 오프코트의 감성을 모두 담아낸 이 신발은 빈티지한 네온 컬러와 클래식한 페이즐리 프린트로 농구의 클래식에 신선한 반전을 더했습니다. 물론 80년대를 떠올리게 하는 구조와 숨겨진 에어 유닛 등 모두가 사랑하는 전설적인 AF1의 감성은 고스란히 재현했죠. 슬램 덩크를 직접 신어 보세요.",
    productColor1: "현재 컬러: 화이트/화이트/민트 폼/팬텀",
    productColor2: "스타일 번호 : FJ7739-101",
    productTitle00: "나이키 에어 포스 1 '07 LX",
    productTitle01: "",
    productTitle02: "",
    productTitle03: "상품 특징",
    productGood01: "",
    productGood02: "",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ견고한 스티칭부터 깔끔한 소재와 컵솔 디자인에 이르기까지 백보드 유리보다 더 매끄럽고 내구성이 좋은 스타일 선사",
    proInfo02:"ㆍ본래 퍼포먼스 농구화를 위해 고안된 나이키 에어 쿠셔닝으로 지속적인 편안함 선사",
    proInfo03:"ㆍ패딩 처리된 로우컷 카라로 날렵한 룩과 편안한 착화감 구현",
    proInfo04:"ㆍ헤리티지 농구 피벗 서클이 새겨진 고무 밑창이 접지력과 내구성 선사",
    historyTit: "에어 포스 1",
    history: "농구 필수 아이템으로 1982년에 출시된 에어 포스 1은 90년대부터 많은 사랑을 받기 시작했습니다. 클래식한 화이트 온 화이트의 AF1이 선보이는 깔끔한 룩은 농구 코트에서부터 스트리트, 일상에 이르기까지 그 인기를 증명했습니다. 에어 포스 1은 힙합 문화에서 자리를 잡고 한정판 컬래버레이션 아이템과 컬러웨이를 선보이며 전 세계적으로 아이코닉한 스니커즈로 성장했습니다. 2,000가지 이상의 버전으로 출시된 이 필수 아이템이 패션과 음악, 스니커즈 문화에 미친 영향은 부정할 수 없습니다.",

    infoImgTit01: "완벽한 내구성 선사",
    infoImgTit02: "가볍고 편안함",
    infoImgTit03: "다양한 연출 가능",
    infoImgTitSub01: "갑피의 직물 오버레이가 내구성과 지지력을 더하며 헤리티지 스타일을 선사합니다.",
    infoImgTitSub02: "본래 퍼포먼스 농구화를 위해 디자인된 나이키 에어 쿠셔닝으로 가볍고 편안한 착화감을 제공합니다.",
    infoImgTitSub03: "로우 컷 실루엣이 깔끔하고 매끈한 룩을 연출합니다.",
    infoImg01: '/img/info_img/lx_01.jpg',
    infoImg02: '/img/info_img/lx_02.jpg',
    infoImg03: '/img/info_img/lx_03.jpg',
},
{
    id : 11,
    title : "나이키 에어맥스 97",
    content : "여성 신발",
    price : 209000,
    url: '/img/item011.webp',
    productInfo: "에어맥스 97로 더욱 앞서가는 스타일을 연출해 보세요. 물결 디자인 라인이 아이코닉한 스니커즈에 속도감이 느껴지는 세련된 룩을 선사합니다. 뉴트럴 베이스와 선명한 컬러가 대비를 이루며 시선을 사로잡는 클래식한 스트리트 스타일을 완성합니다. 또한 전체적으로 적용된 나이키 에어 쿠셔닝을 그대로 유지해 편안한 착용감을 누리며 모두의 관심을 한 몸에 받을 수 있습니다.",
    productColor1: "현재 컬러: 화이트/서밋 화이트/코코넛 밀크/게임 로얄",
    productColor2: "스타일 번호 : FJ5482-100",
    productTitle00: "나이키 에어맥스 97",
    productTitle01: "상품 특징",
    productTitle02: "",
    productTitle03: "상품 상세 정보",
    productGood01: "인조 가죽으로 우수한 내구성을 제공하며 오리지널의 매끄럽고 부드러운 룩 선사",
    productGood02: "",
    productGood03: "",
    productGood04: "",
    proInfo01:"ㆍ설포와 뒤꿈치의 풀 탭",
    proInfo02:"ㆍ폼 중창",
    proInfo03:"ㆍ반사 디테일",
    proInfo04:"ㆍ개인 보호 장비(PPE) 용도로 사용하지 말 것",
    historyTit: "에어맥스 97",
    history: "에어맥스 97의 기원은 도시의 전설이 되었습니다. (물결 디자인에 영감을 준 것은 사실 고속 열차가 아니라 물방울이었지만요.) 그러나 97의 영향력은 여전히 부인할 수 없습니다. 이는 본질적으로 미래를 향한 비전이었으며, 다른 모든 아이콘의 근간이 되었습니다. 이전의 그 어떤 신발과도 달랐죠. 전체적으로 적용된 에어 쿠셔닝과 숨겨진 끈 조임 시스템의 혁신으로 스니커즈 세계에 혁명을 일으켰습니다. 본래 퍼포먼스 러닝화로 제작된 이 신발은 순식간에 밀라노와 같은 하이패션 명소의 스트리트웨어로 선택받았고, 창작자와 아티스트 모두에게 큰 사랑을 받아 스니커즈의 역사에서 확고한 기반을 다졌습니다.",

    infoImgTit01: "나이키 에어맥스 97",
    infoImgTit02: "모델 정보",
    infoImgTit03: "착용 제품",
    infoImgTitSub01: "",
    infoImgTitSub02: "남자 모델 키 : 186cm, 착용 사이즈: 280",
    infoImgTitSub03: "나이키 스포츠웨어 클럽 플리스, 나이키 스포츠웨어 솔로 스우시",
    infoImg01: '/img/info_img/max_01.jpg',
    infoImg02: '/img/info_img/max_02.jpg',
    infoImg03: '/img/info_img/max_03.jpg',
}

];
export default data;
